### ISSUE TITLE
Organization logo

### ISSUE THREAD

**Issue by BondAnthony** [toilops/toilops-logos#1]
toilOps is looking for a community logo that embraces hard working and dedicated system engineers and developers. We develop and operate tools that automate tasks across all levels of the platform.

Tools we use:

- Ansible
- Linux
- Travis
- Shippable
- Python
- Golang
- Chef 

What do we need? We need a logo! Since we develop mostly backend systems our frontend skills are little rough. We would like to see some of the magic the community of graphic designers could come up with. 

Looking for the following logo:
 - Badges - Multiple sizes of badge logos to fit off to the side of posts and favicon.
 - Banner for the top of the site
 - Footer - Clean footer with your signature in the bottom corner. 

Add your Bio link because we will link to your page.

**Comment by Justicimo** [comment]
I'd be happy to help you out, did you have a rough idea of what you were looking for?

**Comment by BondAnthony** [comment]
@Justicimo that would awesome! On the idea front I was thinking tools with a mix of software development stacks, but honestly it can be anything you come up with. I’m open to any idea.

**Comment by Justicimo** [comment]
Here is something I threw together, please don't hesitate to make any suggestions/feedback as it is appreciated. I took more of a material approach here, if you would like to see some other style I'd be glad to switch it up a bit.
![toilops](https://user-images.githubusercontent.com/17466875/31311946-1978863a-ab7d-11e7-8fa9-90d5fa70d159.png)

**Comment by BondAnthony** [comment]
That looks really good! I do like this one, can you open a pull request and submit this logo. Also, any ideas on a smaller logo that combines the two o’s? Would need a logo that fits into a perfect square.

I do like the gears, colors and simplicity of the logo. Great work!

**Comment by Justicimo** [comment]
Of course. Do you have any specific sizes that you would like this in?

**Comment by BondAnthony** [comment]
For the square image probably in the range of 64px x 64px. The full logo could probably be a range of sizes. Could you have a mix of svg and png formats? 

Base logo pixel sizes:
   728 x 90
   468 x 60
 
Squared logo pixel sizes:
  64 x 64
  250 x 250 
  200 x 200

The square logo for a favicon would need to be 16 x 16 or 32 x 32 png format. I'm really curious to see what you come up with for the smaller squared logo. 

Thank you again!

**Comment by Justicimo** [comment]
I was actually thinking the cog would make a good logo for the square. If you had any other suggestions or ideas I'm open to changing it, but that was the intention for it from the start.

**Comment by Justicimo** [comment]
I should also note that the image doesn't exactly fit those dimensions well (728x90 and 468x60) without needing to alter it, stretch it, or having a lot of blank space on the sides. Suggestions on what you wanted me to do here? or were those banner dimensions, so ideally I could make it into a wallpaper?

**Comment by Justicimo** [comment]
![toilopscogtrans250x](https://user-images.githubusercontent.com/17466875/31313354-874fdee6-aba6-11e7-9b0f-85a39cbe3649.png)

![toilopssq250x](https://user-images.githubusercontent.com/17466875/31313356-8c4c7580-aba6-11e7-862d-4f2ab1ea33e5.png)

Here is the cog, the one with no background I think is ideal, but if you need it for something like a mobile app the version with the background is the way to go. Tell me which one you like best or if you have any suggestions to making it better let me know.

**Comment by BondAnthony** [comment]
I do like the idea of having the cog as the square logo or favicon. Could those be svg format also? I do like the black background. The name logo can be any rectangular size if its scalable. 

What do think about toil on top of ops but silghtly off center. The o’s could be cogs that are connected.

I like the other graphics so please go ahead and open a pull request with those and include and portfolio or web address for us to link to your work.

**Comment by Justicimo** [comment]
PRs made. #2 #3 #4 

I do not currently have an up to date portfolio or website at the moment. Tho you can include my name for credit in the contributions files if you'd like. My name is Justice Aranda. :)

**Comment by Justicimo** [comment]
@BondAnthony  I'll look at making a second variant of the logo with your suggestions. I'll keep you posted on it.

**Comment by BondAnthony** [comment]
Awesome thank you @Justicimo they look great!

**Comment by Justicimo** [comment]
Hello Friend,
Here is an update on the second variant you were looking for :)

![toilopsvectorv2](https://user-images.githubusercontent.com/17466875/31580195-09b846ae-b10e-11e7-87d2-62a92430e801.png)

Let me know what you think.

**Comment by BondAnthony** [comment]
Hey that looks good but could the l and p be lined up? Also, is it possible to get the gears fully connected? Maybe the Ops "o" is a little bigger than toil but with the teeth closer together? Let me know what you think.
